[tool.poetry]
name = "11-2-shishkina"
version = "0.1.0"
description = ""
authors = ["nastya shishkina <ana.koze@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
